[build]
  command = "python update_ibex_data.py"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=300"
    X-Frame-Options = "SAMEORIGIN"

[[headers]]
  for = "/ibex_data.json"
  [headers.values]
    Cache-Control = "public, max-age=60"
